#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['idna']

package_data = \
{'': ['*']}

extras_require = \
{'all': ['ruff >= 0.6.2',
         'mypy >= 1.11.2',
         'pytest >= 8.3.2',
         'flake8 >= 7.1.1']}

setup(name='idna',
      version='3.9',
      description='Internationalized Domain Names in Applications (IDNA)',
      author=None,
      author_email='Kim Davies <kim+pypi@gumleaf.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
