#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['idna']

package_data = \
{'': ['*']}

setup(name='idna',
      version='3.8',
      description='Internationalized Domain Names in Applications (IDNA)',
      author=None,
      author_email='Kim Davies <kim+pypi@gumleaf.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
